import { createClient } from 'npm:@supabase/supabase-js@2.57.4';

const TABLE='hc_state',SESS='hc_sync_sessions';
const DEFAULT_CARE=true;
const BULK=['pharmacyDrugs','archive','activity'];
const ALLOWED=new Set(['beds','registry','patients','clinical','inst','archive','activity','chats','pharmacyDrugs','appointments','doctorSchedules']);
const SHARED=new Set(['beds','registry','patients','inst','archive','activity','chats','pharmacyDrugs','appointments','doctorSchedules']);
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'};
const reply=(body:any,status=200)=>new Response(JSON.stringify(body),{status,headers:CORS});
function requirePublishable(req:Request){let keys:any={};try{keys=JSON.parse(Deno.env.get('SUPABASE_PUBLISHABLE_KEYS')||'{}')}catch{}if(!Object.values(keys).map(String).includes(String(req.headers.get('apikey')||'')))throw new Error('Aplicación no autorizada.')}
function db(){let keys:any={};try{keys=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}')}catch{}return createClient(Deno.env.get('SUPABASE_URL')!,String(keys.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||''),{auth:{persistSession:false,autoRefreshToken:false}})}
const hex=(a:Uint8Array)=>Array.from(a).map(x=>x.toString(16).padStart(2,'0')).join('');
async function sha256(s:string){return hex(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))))}
function randomToken(){const a=new Uint8Array(32);crypto.getRandomValues(a);return hex(a)}

async function resolveAuthorized(c:any,token:string,authInstitutionId:string,requestedDataId:string){
  if(!token||!authInstitutionId)throw new Error('Falta sesión o institución.');const h=await sha256(token);
  const {data:seed,error:seedErr}=await c.from('hc_seed_sessions').select('institution_id,expires_at').eq('token_hash',h).maybeSingle();if(seedErr)throw seedErr;
  if(seed&&Date.parse(seed.expires_at)>Date.now()){
    if(String(seed.institution_id)!==authInstitutionId)throw new Error('El admin semilla sólo puede sincronizar la institución vinculada.');
    const {data:i,error:ie}=await c.from('hc_auth_institutions').select('data_institution_id,active').eq('id',authInstitutionId).maybeSingle();if(ie)throw ie;if(!i?.active)throw new Error('La institución no está habilitada.');const dataId=String(i.data_institution_id||authInstitutionId);if(requestedDataId&&requestedDataId!==dataId)throw new Error(`La institución autorizada usa el ámbito de datos ${dataId} y este equipo solicitó ${requestedDataId}.`);c.from('hc_seed_sessions').update({last_seen_at:new Date().toISOString()}).eq('token_hash',h).then(()=>{});return{dataId,username:'admin',role:'admin',access:'rw',seed:true};
  }
  const {data:s,error:se}=await c.from('hc_auth_sessions').select('username,expires_at').eq('token_hash',h).maybeSingle();if(se)throw se;if(!s||Date.parse(s.expires_at)<=Date.now())throw new Error('Sesión institucional inválida o vencida.');
  const {data:u,error:ue}=await c.from('hc_auth_users').select('is_global_admin').eq('username',s.username).maybeSingle();if(ue)throw ue;if(u?.is_global_admin)throw new Error('La cuenta de plataforma no abre datos clínicos.');
  const {data:m,error:me}=await c.from('hc_auth_memberships').select('role,active').eq('username',String(s.username)).eq('institution_id',authInstitutionId).maybeSingle();if(me)throw me;if(!m?.active)throw new Error('No tenés acceso a esa institución.');
  const {data:i,error:ie}=await c.from('hc_auth_institutions').select('data_institution_id,active').eq('id',authInstitutionId).maybeSingle();if(ie)throw ie;if(!i?.active)throw new Error('La institución no está habilitada.');const dataId=String(i.data_institution_id||authInstitutionId);if(requestedDataId&&requestedDataId!==dataId)throw new Error(`La institución autorizada usa el ámbito de datos ${dataId} y este equipo solicitó ${requestedDataId}.`);c.from('hc_auth_sessions').update({last_seen_at:new Date().toISOString()}).eq('token_hash',h).then(()=>{});const role=String(m.role||'');return{dataId,username:String(s.username),role,access:role==='observador'?'ro':'rw',seed:false};
}
async function requireSync(c:any,token:string,institutionId:string){const h=await sha256(token),{data,error}=await c.from(SESS).select('institution_id,expires_at,username,role,access_mode,last_seen_at').eq('token_hash',h).maybeSingle();if(error)throw error;if(!data||String(data.institution_id)!==institutionId||Date.parse(data.expires_at)<=Date.now())throw new Error('Sesión de sincronización inválida o vencida.');if(Date.parse(data.last_seen_at)<Date.now()-60000)await c.from(SESS).update({last_seen_at:new Date().toISOString()}).eq('token_hash',h);return data}

const TIME_KEYS=['updatedAt','editedAt','reportedAt','createdAt','administeredAt','observedAt','pendingNurseAt','nurseSeenAt','dateTime','at','savedAt','startedAt','finishedAt','timestamp','performedAt','completedAt','lastModifiedAt','changedAt'];
const NURSE_KEYS=['pendingNurseAlert','pendingNurseField','pendingNurseAt','nurseSeenAt','nurseSeenByName','pendingHydrationChangeAlert'];
const INSULIN_KEYS=['insulinLastGlucose','insulinLastGlucoseAt','insulinLastActionText','rateMlH','mlHour','dose','doseValue','mlHourLabel','preparationText','updatedAt','updatedByName'];
function timeMs(v:any){const t=Date.parse(String(v||'').replace(' ','T'));return Number.isFinite(t)?t:0}
function stamp(v:any,d=0):number{if(v==null||d>5)return 0;if(Array.isArray(v))return v.reduce((m,x)=>Math.max(m,stamp(x,d+1)),0);if(typeof v!=='object')return 0;let m=0;for(const k of TIME_KEYS)m=Math.max(m,timeMs(v[k]));if(d<3)for(const[k,x]of Object.entries(v))if(!TIME_KEYS.includes(k)&&Array.isArray(x))m=Math.max(m,stamp(x,d+1));return m}
function nurseStamp(v:any){return v&&typeof v==='object'?Math.max(timeMs(v.pendingNurseAt),timeMs(v.nurseSeenAt),stamp(Array.isArray(v.administrationRecords)?v.administrationRecords:[])):0}
function identity(v:any,i:number){if(v&&typeof v==='object'&&!Array.isArray(v)){for(const k of['id','recordId','requestId','slotKey','key']){const x=String(v[k]??'').trim();if(x)return`${k}:${x}`}const at=String(v.dateTime||v.at||v.createdAt||v.reportedAt||v.administeredAt||v.ts||''),by=String(v.by||v.byName||v.createdBy||v.createdByName||v.user||''),type=String(v.type||v.status||v.name||v.label||v.kind||'');if(at||by||type)return`meta:${at}|${by}|${type}`;try{return`json:${JSON.stringify(v)}`}catch{return`idx:${i}`}}return`primitive:${typeof v}:${String(v)}`}
function isRx(v:any){return!!(v&&typeof v==='object'&&!Array.isArray(v)&&String(v.id||'')&&('drugId'in v||'insulinProtocol'in v||'heparinProtocol'in v||'administrationMode'in v))}
function mergeArray(a:any[],b:any[]){a=Array.isArray(a)?a:[];b=Array.isArray(b)?b:[];const map=new Map<string,any>();a.forEach((x,i)=>map.set(identity(x,i),x));const used=new Set<string>(),out=b.map((x,i)=>{const k=identity(x,i),p=map.get(k);used.add(k);return p===undefined?x:mergeValue(p,x)});a.forEach((x,i)=>{const k=identity(x,i);if(!used.has(k))out.push(x)});return out}
function mergeObject(a:any,b:any){a=a&&typeof a==='object'&&!Array.isArray(a)?a:{};b=b&&typeof b==='object'&&!Array.isArray(b)?b:{};const newer=stamp(b)>=stamp(a)?b:a,older=newer===b?a:b,out:any={...older,...newer},keys=new Set([...Object.keys(a),...Object.keys(b)]);for(const k of keys){if(!(k in a)){out[k]=b[k];continue}if(!(k in b)){out[k]=a[k];continue}const x=a[k],y=b[k];if(Array.isArray(x)||Array.isArray(y))out[k]=mergeArray(Array.isArray(x)?x:[],Array.isArray(y)?y:[]);else if(x&&y&&typeof x==='object'&&typeof y==='object')out[k]=mergeObject(x,y)}if(isRx(a)||isRx(b)){const ai=timeMs(a.insulinLastGlucoseAt),bi=timeMs(b.insulinLastGlucoseAt),src=bi>ai?b:ai>bi?a:newer;if(ai||bi)for(const k of INSULIN_KEYS)if(Object.prototype.hasOwnProperty.call(src,k))out[k]=src[k]}if(NURSE_KEYS.some(k=>Object.prototype.hasOwnProperty.call(a,k)||Object.prototype.hasOwnProperty.call(b,k))){const A=nurseStamp(a),B=nurseStamp(b),src=B>A?b:A>B?a:newer;for(const k of NURSE_KEYS)if(Object.prototype.hasOwnProperty.call(src,k))out[k]=src[k];if(timeMs(out.pendingNurseAt)&&timeMs(out.nurseSeenAt)>=timeMs(out.pendingNurseAt)){out.pendingNurseAlert=false;out.pendingNurseField=''}}return out}
function mergeValue(a:any,b:any):any{if(a===undefined)return b;if(b===undefined)return a;if(Array.isArray(a)||Array.isArray(b))return mergeArray(Array.isArray(a)?a:[],Array.isArray(b)?b:[]);if(a&&b&&typeof a==='object'&&typeof b==='object')return mergeObject(a,b);return b}
function mergePayload(a:any,b:any){a=a&&typeof a==='object'?a:{};b=b&&typeof b==='object'?b:{};return Object.prototype.hasOwnProperty.call(a,'value')||Object.prototype.hasOwnProperty.call(b,'value')?{...a,...b,value:mergeValue(a.value,b.value)}:mergeObject(a,b)}
function canonical(v:any){const walk=(x:any):any=>Array.isArray(x)?x.map(walk):x&&typeof x==='object'?Object.keys(x).sort().reduce((o:any,k)=>(o[k]=walk(x[k]),o),{}):x;try{return JSON.stringify(walk(v))}catch{return JSON.stringify(v)}}
const COLS='institution_id,bucket,record_id,payload,sort_index,deleted,updated_at,revision,sync_seq,writer';
function normalizeRows(raw:any[],institutionId:string){return(Array.isArray(raw)?raw:[]).map((r:any)=>{const bucket=String(r.bucket||'');if(!ALLOWED.has(bucket))throw new Error('Bucket no permitido.');return{institution_id:institutionId,bucket,record_id:String(r.record_id||'main'),payload:r.payload??{},sort_index:Number(r.sort_index)||0,deleted:!!r.deleted,writer:String(r.writer||'').slice(0,160)}})}
async function prepareChanged(c:any,institutionId:string,raw:any[]){const rows=normalizeRows(raw,institutionId);if(!rows.length)return[];const buckets=Array.from(new Set(rows.map((r:any)=>r.bucket))),ids=Array.from(new Set(rows.map((r:any)=>r.record_id))),{data,error}=await c.from(TABLE).select('bucket,record_id,payload,sort_index,deleted').eq('institution_id',institutionId).in('bucket',buckets).in('record_id',ids);if(error)throw error;const map=new Map((data||[]).map((x:any)=>[`${x.bucket}\u0000${x.record_id}`,x])),out:any[]=[];for(const r of rows){const prev:any=map.get(`${r.bucket}\u0000${r.record_id}`);if(prev&&!r.deleted&&!prev.deleted&&(r.bucket==='clinical'||SHARED.has(r.bucket)))r.payload=mergePayload(prev.payload,r.payload);const same=!!prev&&!!prev.deleted===!!r.deleted&&Number(prev.sort_index||0)===Number(r.sort_index||0)&&canonical(prev.payload)===canonical(r.payload);if(!same)out.push(r)}return out}
// Compare-and-swap keeps a concurrent nursing save from replacing a new medical order.
async function writeClinical(c:any,institutionId:string,input:any){
 const row=normalizeRows([input],institutionId)[0];
 for(let attempt=0;attempt<6;attempt++){
  const q=await c.from(TABLE).select('payload,revision,deleted,sort_index').eq('institution_id',institutionId).eq('bucket',row.bucket).eq('record_id',row.record_id).maybeSingle();if(q.error)throw q.error;
  const prev=q.data,next={...row};if(prev&&!next.deleted&&!prev.deleted)next.payload=mergePayload(prev.payload,next.payload);
  if(prev&&!!prev.deleted===!!next.deleted&&Number(prev.sort_index||0)===next.sort_index&&canonical(prev.payload)===canonical(next.payload))return 0;
  if(prev){const u=await c.from(TABLE).update({payload:next.payload,deleted:next.deleted,sort_index:next.sort_index,writer:next.writer}).eq('institution_id',institutionId).eq('bucket',row.bucket).eq('record_id',row.record_id).eq('revision',prev.revision).select('revision');if(u.error)throw u.error;if(u.data?.length)return 1;}
  else{const u=await c.from(TABLE).insert(next).select('revision');if(!u.error)return 1;if(u.error.code!=='23505')throw u.error;}
 }
 throw Error('Hubo cambios concurrentes; el envío se conserva y se reintentará.');
}
async function writeRows(c:any,institutionId:string,raw:any[]){
 const ordered=raw.slice().sort((a,b)=>{const A=a.bucket==='clinical'?0:1,B=b.bucket==='clinical'?0:1;return A-B||String(a.bucket).localeCompare(String(b.bucket))||String(a.record_id).localeCompare(String(b.record_id));});let count=0;
 for(const r of ordered.filter(x=>x.bucket==='clinical'))count+=await writeClinical(c,institutionId,r);
 const shared=ordered.filter(x=>x.bucket!=='clinical');for(let i=0;i<shared.length;i+=20){const rows=await prepareChanged(c,institutionId,shared.slice(i,i+20));if(rows.length){const r=await c.from(TABLE).upsert(rows,{onConflict:'institution_id,bucket,record_id'});if(r.error)throw r.error;count+=rows.length;}}
 return count;
}
async function changes(c:any,institutionId:string,afterSeq:number,limit:number,care=false){
 let q=c.from(TABLE).select(COLS).eq('institution_id',institutionId).gt('sync_seq',afterSeq);if(care)q=q.not('bucket','in','('+BULK.join(',')+')');
 const r=await q.order('sync_seq',{ascending:true}).limit(limit);if(r.error)throw r.error;const rows=r.data||[];return{rows,nextSeq:rows.reduce((m:any,x:any)=>Math.max(m,Number(x.sync_seq||0)),afterSeq),hasMore:rows.length===limit};
}
async function head(c:any,institutionId:string){const {data,error}=await c.from(TABLE).select('sync_seq,updated_at,revision,record_id').eq('institution_id',institutionId).order('sync_seq',{ascending:false}).limit(1);if(error)throw error;return{syncSeq:Number(data?.[0]?.sync_seq||0),updatedAt:data?.[0]?.updated_at||'',revision:data?.[0]?.revision||0,recordId:data?.[0]?.record_id||''}}

Deno.serve(async(req:Request)=>{
  if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});
  try{
    requirePublishable(req);const b=await req.json(),action=String(b.action||''),c=db();
    if(action==='bootstrap'){
      const x=await resolveAuthorized(c,String(b.globalToken||''),String(b.institutionId||''),String(b.dataInstitutionId||b.institutionId||''));const syncToken=randomToken(),token_hash=await sha256(syncToken),now=new Date(),expires=new Date(now.getTime()+12*3600000);await c.from(SESS).delete().lt('expires_at',now.toISOString());const {error}=await c.from(SESS).insert({token_hash,institution_id:x.dataId,expires_at:expires.toISOString(),last_seen_at:now.toISOString(),username:x.username,role:x.role,access_mode:x.access});if(error)throw error;return reply({ok:true,syncToken,expiresAt:expires.toISOString(),syncVersion:15,dataInstitutionId:x.dataId,role:x.role,accessMode:x.access,seed:!!x.seed});
    }
    const care=DEFAULT_CARE||b.lane==='care';const institutionId=String(b.institutionId||''),s=await requireSync(c,String(b.syncToken||''),institutionId),ro=String(s.access_mode)==='ro';
    if(action==='bulkInfo'){const r=await c.from(TABLE).select('bucket,record_id,revision,sync_seq,deleted').eq('institution_id',institutionId).in('bucket',BULK).eq('record_id','main');if(r.error)throw r.error;return reply({ok:true,entries:r.data||[]});}
    if(action==='bulkPage'){if(!BULK.includes(String(b.bucket||'')))throw Error('Catálogo no permitido.');const r=await c.rpc('hc281_bulk_page',{p_institution:institutionId,p_bucket:b.bucket,p_offset:Math.max(0,Number(b.offset)||0),p_limit:Math.min(8,Math.max(1,Number(b.limit)||5))});if(r.error)throw r.error;return reply({ok:true,...r.data});}
    if(action==='head')return reply({ok:true,...await head(c,institutionId),syncVersion:15,readOnly:ro});
    if(action==='pull'){let q=c.from(TABLE).select(COLS).eq('institution_id',institutionId);if(care)q=q.not('bucket','in','('+BULK.join(',')+')');const buckets=Array.isArray(b.buckets)?Array.from(new Set(b.buckets.map(String).filter((x:string)=>ALLOWED.has(x)))):[];if(buckets.length)q=q.in('bucket',buckets);const {data,error}=await q.order('bucket').order('sort_index');if(error)throw error;return reply({ok:true,rows:data||[],syncSeq:(await head(c,institutionId)).syncSeq,syncVersion:15,filtered:buckets.length>0,buckets,readOnly:ro})}
    if(action==='changes'){const d=await changes(c,institutionId,Math.max(0,Number(b.afterSeq||0)),Math.min(1000,Math.max(1,Number(b.limit||500))),care);return reply({ok:true,...d,syncVersion:15,incremental:true,readOnly:ro})}
    if(action==='sync'){if(ro&&Array.isArray(b.rows)&&b.rows.length)throw new Error('Modo Observador: la sesión es de solo lectura.');const submitted=Array.isArray(b.rows)?b.rows:[];if(care&&submitted.some((r:any)=>BULK.includes(r.bucket)))throw Error('Los catálogos se envían por separado.');const written=ro?0:await writeRows(c,institutionId,submitted.map((r:any)=>({...r,writer:s.username}))),d=await changes(c,institutionId,Math.max(0,Number(b.afterSeq||0)),Math.min(1000,Math.max(1,Number(b.limit||500))),care);return reply({ok:true,...d,written,acknowledged:submitted.map((r:any)=>({bucket:r.bucket,record_id:r.record_id})),syncVersion:15,duplex:true,care,readOnly:ro})}
    if(action==='upsert'){if(ro)throw new Error('Modo Observador: la sesión es de solo lectura.');const written=await writeRows(c,institutionId,(Array.isArray(b.rows)?b.rows:[]).map((r:any)=>({...r,writer:s.username})));return reply({ok:true,count:written,...await head(c,institutionId),mergeVersion:12,syncVersion:15})}
    if(action==='deleteClinicalMissing'){if(ro)throw new Error('Modo Observador: la sesión es de solo lectura.');if(b.allowDelete!==true)return reply({ok:true,deleted:0,protected:true});const prefix=String(b.pidPrefix||''),keep=Array.isArray(b.keep)?b.keep.map(String):[],{data,error}=await c.from(TABLE).select('record_id').eq('institution_id',institutionId).eq('bucket','clinical').like('record_id',prefix+'%');if(error)throw error;const missing=(data||[]).map((x:any)=>String(x.record_id)).filter((x:string)=>!keep.includes(x));if(missing.length){const e=(await c.from(TABLE).update({deleted:true,writer:'v232'}).eq('institution_id',institutionId).eq('bucket','clinical').in('record_id',missing)).error;if(e)throw e}return reply({ok:true,deleted:missing.length})}
    if(action==='count'){const {count,error}=await c.from(TABLE).select('*',{count:'exact',head:true}).eq('institution_id',institutionId);if(error)throw error;return reply({ok:true,count:count||0,syncVersion:15,readOnly:ro})}
    return reply({ok:false,error:'Acción no reconocida.'},400);
  }catch(e){return reply({ok:false,error:String((e as any)?.message||e)},400)}
});

