import { createClient } from 'npm:@supabase/supabase-js@2.57.4';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type, apikey','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'};
const reply=(b:any,status=200)=>new Response(JSON.stringify(b),{status,headers:cors});
function db(){let k:any={};try{k=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}')}catch{}return createClient(Deno.env.get('SUPABASE_URL')!,String(k.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||''),{auth:{persistSession:false,autoRefreshToken:false}})}
async function hash(s:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(x=>x.toString(16).padStart(2,'0')).join('');}
function canonical(v:any){const sorted=(x:any):any=>Array.isArray(x)?x.map(sorted):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,sorted(x[k])])):x;return JSON.stringify(sorted(v));}
async function authorize(c:any,token:string,inst:string){if(!token||!inst)throw Error('Falta autorización institucional.');const r=await c.from('hc_auth_sessions').select('username,expires_at').eq('token_hash',await hash(token)).maybeSingle();if(r.error)throw r.error;if(!r.data||Date.parse(r.data.expires_at)<=Date.now())throw Error('Sesión vencida.');const u=await c.from('hc_auth_users').select('username,name,active,is_global_admin').eq('username',r.data.username).maybeSingle();if(u.error)throw u.error;if(!u.data?.active||u.data.is_global_admin)throw Error('Ingresá con una cuenta institucional de laboratorio.');const m=await c.from('hc_auth_memberships').select('role,active,hc_auth_institutions(active,data_institution_id)').eq('username',u.data.username).eq('institution_id',inst).maybeSingle();if(m.error)throw m.error;if(!m.data?.active||!m.data.hc_auth_institutions?.active||!['bioquimico','admin'].includes(m.data.role))throw Error('Sólo laboratorio y administración institucional pueden revisar estos envíos.');return {username:u.data.username,name:u.data.name||u.data.username,dataId:String(m.data.hc_auth_institutions.data_institution_id||inst)};}
export function normalizeMessage(raw:any){const s=(v:any,max=200)=>String(v??'').trim().slice(0,max);if(!raw||raw.schema!=='hospitalito.lab.v1')throw Error('Formato esperado: hospitalito.lab.v1.');const m={schema:'hospitalito.lab.v1',patientId:s(raw.patientId,100),requestId:s(raw.requestId,100),messageId:s(raw.messageId,160),source:s(raw.source,80),freeNote:s(raw.freeNote,4000),resultRows:[] as any[],resultText:''};if(!m.patientId||!m.requestId||!m.messageId||!m.source)throw Error('Faltan paciente, solicitud, origen o identificador del envío.');if(!/^[A-Za-z0-9_-]+$/.test(m.patientId))throw Error('Identificador de paciente inválido.');if(!Array.isArray(raw.resultRows)||!raw.resultRows.length||raw.resultRows.length>200)throw Error('El envío debe contener entre 1 y 200 determinaciones.');m.resultRows=raw.resultRows.map((x:any)=>({key:s(x.key,80),label:s(x.label,120),value:s(x.value,400),unit:s(x.unit,80),ref:s(x.ref,160),flag:s(x.flag,30)}));if(m.resultRows.some(x=>!x.key||!x.label||!x.value))throw Error('Cada determinación requiere código, nombre y valor.');if(new Set(m.resultRows.map(x=>x.key)).size!==m.resultRows.length)throw Error('Hay determinaciones duplicadas.');m.resultText=m.resultRows.map(x=>`${x.label}: ${x.value}${x.unit?' '+x.unit:''}${x.ref?' · referencia '+x.ref:''}${x.flag?' · '+x.flag:''}`).join('\n');return m;}
Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});
 try{let keys:any={};try{keys=JSON.parse(Deno.env.get('SUPABASE_PUBLISHABLE_KEYS')||'{}')}catch{}if(!Object.values(keys).includes(req.headers.get('apikey')))throw Error('Aplicación no autorizada.');if(req.method!=='POST')throw Error('Método no permitido.');const raw=await req.text();if(raw.length>160000)throw Error('Envío demasiado grande.');const b=JSON.parse(raw),c=db(),u=await authorize(c,String(b.token||''),String(b.institutionId||'')),action=String(b.action||'');
  if(action==='list'){let q=c.from('hc_lab_inbox').select('id,patient_id,request_id,source,message_id,payload,status,received_at').eq('institution_id',u.dataId).eq('status','pending');if(b.patientId)q=q.eq('patient_id',String(b.patientId));const r=await q.order('received_at',{ascending:false}).limit(100);if(r.error)throw r.error;return reply({ok:true,messages:r.data||[]});}
  if(action==='receive'){const m=normalizeMessage(b.message);const r=await c.from('hc_state').select('payload').eq('institution_id',u.dataId).eq('bucket','clinical').eq('record_id',m.patientId+'::labRequests').eq('deleted',false).maybeSingle();if(r.error)throw r.error;const request=(r.data?.payload?.value||[]).find((x:any)=>x.id===m.requestId);if(!request||request.completed)throw Error('La solicitud no existe o ya está informada. Esperá su sincronización y verificá la vinculación de muestra.');const prior=await c.from('hc_lab_inbox').select('id,payload,status').eq('institution_id',u.dataId).eq('source',m.source).eq('message_id',m.messageId).maybeSingle();if(prior.error)throw prior.error;if(prior.data){if(canonical(prior.data.payload)!==canonical(m))throw Error('El identificador del envío ya se usó con otro contenido.');return reply({ok:true,id:prior.data.id,duplicate:true,status:prior.data.status});}const ins=await c.from('hc_lab_inbox').insert({institution_id:u.dataId,patient_id:m.patientId,request_id:m.requestId,message_id:m.messageId,source:m.source,payload:m,received_by:u.username}).select('id').single();if(ins.error)throw ins.error;return reply({ok:true,id:ins.data.id,status:'pending'});}
  if(action==='approve'){const r=await c.rpc('hc280_approve_lab',{p_institution:u.dataId,p_id:String(b.id||''),p_user:u.username,p_name:u.name});if(r.error)throw r.error;return reply(r.data);}
  if(action==='reject'){const r=await c.from('hc_lab_inbox').update({status:'rejected',reviewed_at:new Date().toISOString(),reviewed_by:u.username}).eq('id',String(b.id||'')).eq('institution_id',u.dataId).eq('status','pending');if(r.error)throw r.error;return reply({ok:true});}
  throw Error('Acción no permitida.');
 }catch(e){return reply({ok:false,error:String((e as any)?.message||e)},400);}
});
