import { createClient } from 'npm:@supabase/supabase-js@2.57.4';
import { generateRegistrationOptions, verifyRegistrationResponse, generateAuthenticationOptions, verifyAuthenticationResponse } from 'npm:@simplewebauthn/server@13.2.2';

// No biometric images/templates leave the authenticator. Only public keys are stored.
const RP_ID='walterrigoni.github.io',ORIGIN='https://walterrigoni.github.io';
const CORS={'Access-Control-Allow-Origin':ORIGIN,'Access-Control-Allow-Headers':'content-type, apikey','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'};
const reply=(b:any,status=200)=>new Response(JSON.stringify(b),{status,headers:CORS});
const hex=(a:Uint8Array)=>Array.from(a).map(x=>x.toString(16).padStart(2,'0')).join('');
const b64=(a:Uint8Array)=>btoa(String.fromCharCode(...a));
const unb64=(s:string)=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const token=()=>{const a=new Uint8Array(32);crypto.getRandomValues(a);return hex(a);};
async function hash(s:string){return hex(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))))}
function db(){let keys:any={};try{keys=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}')}catch{}return createClient(Deno.env.get('SUPABASE_URL')!,String(keys.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||''),{auth:{persistSession:false,autoRefreshToken:false}})}
function checkApp(req:Request){let keys:any={};try{keys=JSON.parse(Deno.env.get('SUPABASE_PUBLISHABLE_KEYS')||'{}')}catch{}if(!Object.values(keys).includes(req.headers.get('apikey')))throw Error('Aplicación no autorizada.');if(req.headers.get('origin')!==ORIGIN)throw Error('Las llaves de acceso se usan desde la web segura de Hospitalito.');}
async function userBySession(c:any,raw:string){if(!raw)throw Error('Ingresá primero con tu contraseña.');const {data:s,error}=await c.from('hc_auth_sessions').select('username,expires_at,created_at').eq('token_hash',await hash(raw)).maybeSingle();if(error)throw error;if(!s||Date.parse(s.expires_at)<=Date.now())throw Error('Ingresá primero con tu contraseña.');const {data:u,error:e}=await c.from('hc_auth_users').select('*').eq('username',s.username).eq('active',true).maybeSingle();if(e)throw e;if(!u)throw Error('Cuenta deshabilitada.');return {user:u,session:s};}
async function credentials(c:any,username:string){const r=await c.from('hc_passkeys').select('*').eq('username',username).is('revoked_at',null);if(r.error)throw r.error;return r.data||[];}
async function saveChallenge(c:any,username:string,kind:string,challenge:string,rawToken=''){const r=await c.from('hc_passkey_challenges').insert({username,kind,challenge,origin:ORIGIN,token_hash:rawToken?await hash(rawToken):null,expires_at:new Date(Date.now()+120000).toISOString()}).select('id').single();if(r.error)throw r.error;return r.data.id;}
async function consumeChallenge(c:any,id:string,kind:string,username:string,rawToken=''){if(!id)throw Error('Falta el desafío de seguridad.');const r=await c.from('hc_passkey_challenges').delete().eq('id',id).eq('kind',kind).eq('username',username).gt('expires_at',new Date().toISOString()).select('*').maybeSingle();if(r.error)throw r.error;const d=r.data;if(!d||d.origin!==ORIGIN||rawToken&&d.token_hash!==await hash(rawToken))throw Error('Verificación vencida o ya utilizada. Volvé a intentar.');return d.challenge;}
function publicUser(u:any){const p=u.profile||{};return {username:u.username,name:u.name||u.username,role:u.default_role||'medico',email:u.email||'',active:u.active!==false,isGlobalAdmin:!!u.is_global_admin,mustChangePassword:!!u.must_change_password,...Object.fromEntries(['phone','specialty','licenseNumber','professionalTitle','photo','signature','signatureUpdatedAt','uiTheme','preferences'].map(k=>[k,p[k]??(k==='preferences'?{}:'')]))};}
async function issueSession(c:any,user:any){const raw=token(),now=new Date();const r=await c.from('hc_auth_sessions').insert({token_hash:await hash(raw),username:user.username,expires_at:new Date(Date.now()+24*3600000).toISOString(),last_seen_at:now.toISOString()});if(r.error)throw r.error;let institutions:any[]=[];
 if(user.is_global_admin){const r=await c.from('hc_auth_institutions').select('*').eq('active',true);if(r.error)throw r.error;institutions=r.data.map((i:any)=>({id:String(i.id),name:i.name,displayName:i.display_name||'',role:'superadmin',dataInstitutionId:String(i.data_institution_id||i.id),active:true,logoData:i.logo_data||''}));}
 else{const r=await c.from('hc_auth_memberships').select('role,institution_id,hc_auth_institutions(*)').eq('username',user.username).eq('active',true);if(r.error)throw r.error;institutions=(r.data||[]).filter((m:any)=>m.hc_auth_institutions?.active!==false).map((m:any)=>({id:String(m.institution_id),name:m.hc_auth_institutions.name,displayName:m.hc_auth_institutions.display_name||'',role:m.role,dataInstitutionId:String(m.hc_auth_institutions.data_institution_id||m.institution_id),active:true,logoData:m.hc_auth_institutions.logo_data||''}));if(!institutions.length)throw Error('La cuenta no tiene instituciones habilitadas.');}
 return {ok:true,token:raw,user:publicUser(user),institutions};
}
Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});
 try{checkApp(req);if(req.method!=='POST')throw Error('Método no permitido.');const raw=await req.text();if(raw.length>64000)throw Error('Solicitud demasiado grande.');const b=JSON.parse(raw),c=db(),action=String(b.action||'');
  if(['list','registerOptions','registerVerify','revoke'].includes(action)){
   const {user,session}=await userBySession(c,String(b.token||''));
   if(action==='list')return reply({ok:true,credentials:(await credentials(c,user.username)).map((x:any)=>({id:x.id,label:x.label,createdAt:x.created_at}))});
   // Registration/revocation require a recent password proof, not a stale session.
   if(action!=='registerVerify'&&Date.now()-Date.parse(session.created_at)>300000)throw Error('Para modificar tu acceso, confirmá nuevamente tu contraseña.');
   if(action==='revoke'){const r=await c.from('hc_passkeys').update({revoked_at:new Date().toISOString()}).eq('id',String(b.credentialId||'')).eq('username',user.username);if(r.error)throw r.error;return reply({ok:true});}
   if(user.must_change_password)throw Error('Primero cambiá tu contraseña inicial.');
   if(action==='registerOptions'){const items=await credentials(c,user.username);const options=await generateRegistrationOptions({rpName:'Hospitalito',rpID:RP_ID,userName:user.username,userDisplayName:user.name||user.username,userID:new TextEncoder().encode(user.username),attestationType:'none',excludeCredentials:items.map((x:any)=>({id:x.id,transports:x.transports})),authenticatorSelection:{residentKey:'required',userVerification:'required'}});const challengeId=await saveChallenge(c,user.username,'registration',options.challenge,String(b.token));return reply({ok:true,options,challengeId});}
   const challenge=await consumeChallenge(c,String(b.challengeId),'registration',user.username,String(b.token));const verification=await verifyRegistrationResponse({response:b.response,expectedChallenge:challenge,expectedOrigin:ORIGIN,expectedRPID:RP_ID,requireUserVerification:true});if(!verification.verified||!verification.registrationInfo)throw Error('El dispositivo no pudo verificarse.');const i=verification.registrationInfo,credential=i.credential;const r=await c.from('hc_passkeys').insert({id:credential.id,username:user.username,public_key:b64(credential.publicKey),counter:credential.counter,transports:credential.transports||[],device_type:i.credentialDeviceType,backed_up:i.credentialBackedUp,label:String(b.label||'Mi dispositivo').slice(0,80)});if(r.error)throw r.error;return reply({ok:true});
  }
  if(action==='authOptions'){
   const username=String(b.username||'').trim();const r=await c.from('hc_auth_users').select('username,active').ilike('username',username).limit(1).maybeSingle();if(r.error)throw r.error;if(!r.data?.active)throw Error('No se pudo iniciar el acceso con dispositivo. Usá tu contraseña.');const keys=await credentials(c,r.data.username);if(!keys.length)throw Error('Ingresá con contraseña y activá tu dispositivo en Cuenta → Acceso seguro.');
   const options=await generateAuthenticationOptions({rpID:RP_ID,allowCredentials:keys.map((x:any)=>({id:x.id,transports:x.transports})),userVerification:'required'});return reply({ok:true,username:r.data.username,options,challengeId:await saveChallenge(c,r.data.username,'authentication',options.challenge)});
  }
  if(action==='authVerify'){
   const username=String(b.username||''),challenge=await consumeChallenge(c,String(b.challengeId),'authentication',username);const r=await c.from('hc_passkeys').select('*').eq('id',String(b.response?.id||'')).eq('username',username).is('revoked_at',null).maybeSingle();if(r.error)throw r.error;if(!r.data)throw Error('Llave de acceso inválida.');const key=r.data;
   const v=await verifyAuthenticationResponse({response:b.response,expectedChallenge:challenge,expectedOrigin:ORIGIN,expectedRPID:RP_ID,requireUserVerification:true,credential:{id:key.id,publicKey:unb64(key.public_key),counter:Number(key.counter),transports:key.transports||[]}});if(!v.verified)throw Error('No se pudo verificar el dispositivo.');
   const u=await c.from('hc_auth_users').select('*').eq('username',username).eq('active',true).maybeSingle();if(u.error)throw u.error;if(!u.data||u.data.must_change_password)throw Error('Ingresá con contraseña para revisar tu cuenta.');const update=await c.from('hc_passkeys').update({counter:v.authenticationInfo.newCounter}).eq('id',key.id).eq('counter',key.counter).is('revoked_at',null).select('id').maybeSingle();if(update.error)throw update.error;if(!update.data)throw Error('La llave cambió durante la verificación; intentá nuevamente.');return reply(await issueSession(c,u.data));
  }
  throw Error('Acción no permitida.');
 }catch(e){return reply({ok:false,error:String((e as any)?.message||e)},400);}
});
